[package]
name = "ntscrt"
version = "0.1.2"
edition = "2021"
description = "Cross-platform NTSCRT frontend for Windows and Linux"
license = "GPL-3.0-only"

[dependencies]
anyhow = "1.0"
eframe = { version = "0.33.3", default-features = false, features = [
    "default_fonts",
    "glow",
    "persistence",
    "wayland",
    "x11",
] }
image = { version = "0.25.8", default-features = false, features = [
    "bmp",
    "gif",
    "jpeg",
    "png",
    "tga",
    "webp",
] }
librashader = { git = "https://github.com/SnowflakePowered/librashader.git", rev = "0fb80618b071b6ad25b66b979a4908de531d764c", default-features = false, features = [
    "presets",
    "runtime-wgpu",
    "stable",
] }
ntsc-rs = { path = "../Vendor/ntsc-rs/crates/ntscrs" }
parking_lot = "0.12"
pollster = "0.4"
rfd = { version = "0.15.3", default-features = false, features = [
    "async-std",
    "xdg-portal",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wgpu29 = { package = "wgpu", version = "29.0.3" }

[profile.release]
codegen-units = 1
lto = "thin"
strip = true

[workspace]
